site:
    title: 'Walking On A Rat Trail'
    description: 'Describe the mind of an anarcho-green sweeted neglected misery figure'
    author: Mike Würfel <news@young-workers.de>
    pretty_urls: false
    output: '.'
    
smartypants:
    enable: true
